#!/bin/sh

./fifoxRemove
./msfontsInstall
./atualizar
./braveInstall
./chromeInstall
#./vsCodeInstall
./rInstall
#./arduinoInstall

sudo apt autoclean -y
sudo apt autoremove -y

echo reiniciando
shutdown -r now

