#!/bin/sh

ARQUIVO="arduino-1.8.13"

installed=$(dpkg -s arduino | grep "Status: install ok installed")

ATUAL=$(pwd)
TEMP=$(mktemp --directory)
cd $TEMP

if [ "$installed" = "" ]; then

    wget https://downloads.arduino.cc/"$ARQUIVO"-linux64.tar.xz

    sudo tar -xf "$ARQUIVO"-linux64.tar.xz

    sudo mv "$ARQUIVO" "$HOME/$ARQUIVO"

    cd "$HOME/$ARQUIVO"

    sudo ./install.sh

    curl -fsSL https://raw.githubusercontent.com/arduino/arduino-cli/master/install.sh | sh

    export PATH=$PATH:$HOME/$ARQUIVO/bin

    arduino-cli lib install "RTClib"
    arduino-cli update
    arduino-cli upgrade

    echo "Deseja Cadastrar Usuário?(S/N)"
    read result

    if [ "${result^^}" == "S" ]
    then
        echo "Usuário: "
        read USER

        sudo adduser "$USER" dialout
        sudo chmod a+rw /dev/ttyACM0
    fi

else
	echo "$0: Programa Já Foi Instalado"
fi 

cd $ATUAL
rm -rf $TEMP



