#!/bin/sh

installed=$(dpkg -s google-chrome-stable | grep "Status: install ok installed")

mkdir temp
cd temp
if [ "$installed" = "" ]; then
	wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
	sudo dpkg -i google-chrome-stable_current_amd64.deb
else
	echo "Programa Já Foi Instalado"
fi


cd ..
rm temp -r

