#!/bin/sh
pack="code --install-extension"
installed=$(dpkg -s code | grep "Status: install ok installed")

mkdir temp
cd temp
if [ "$installed" = "" ]; then
    wget https://go.microsoft.com/fwlink/?LinkID=760868
    sudo dpkg -i *
else
	echo "$0: Programa Já Foi Instalado"
fi 

${pack} ms-ceintl.vscode-language-pack-pt-br
${pack} ms-vscode.cpptools
${pack} ms-vscode.cmake-tools
${pack} coenraads.bracket-pair-colorizer-2

cd ..
rm temp -r
