#!/bin/sh
ATUAL=$(pwd)
installed=$(dpkg -s gzdoom | grep "Status: install ok installed")

TEMP=$(mktemp --directory)
cd $TEMP

if [ "$installed" = "" ]; then
    wget https://github.com/coelckers/gzdoom/releases/download/g4.5.0/gzdoom_4.5.0_amd64.deb
    sudo dpkg -i *
    wget https://github.com/Akbar30Bill/DOOM_wads/raw/master/heretic.wad
    mv heretic.wad ~/.config/gzdoom/heretic.wad
else
	echo "$0: Programa Já Foi Instalado"
fi 

cd $ATUAL
rm -rf $TEMP

#https://github.com/Akbar30Bill/DOOM_wads
#https://github.com/coelckers/wadext/releases/tag/1.0
#http://www.gamersonlinux.com/forum/threads/brutal-heretic-guide.2473/
