#!/bin/sh

PAC="zdoom"
installed=$(sudo dpkg -s PAC | grep "Status: install ok installed")

ATUAL=$(pwd)
TEMP=$(mktemp --directory)
cd $TEMP

if [ "$installed" = "" ]; then
    wget https://github.com/Akbar30Bill/DOOM_wads/raw/master/heretic.wad
    if [ "${PAC}" = "gzdoom"]; then
        wget https://github.com/coelckers/gzdoom/releases/download/g4.5.0/gzdoom_4.5.0_amd64.deb
        sudo dpkg -i gzdoom_4.5.0_amd64.deb
        gzdoom    
        mv heretic.wad ~/.config/gzdoom/heretic.wad
    fi
    if [ "${PAC}" = "lzdoom"]; then
        wget https://github.com/coelckers/gzdoom/releases/download/g4.3.3/gzdoom_4.3.3_amd64.deb
        sudo dpkg -i lzdoom_3.87b_amd64.deb
        lzdoom
        mv heretic.wad ~/.config/lzdoom/heretic.wad
    fi
else
	echo "$0: Programa Já Foi Instalado"
fi 

cd $ATUAL
rm -rf $TEMP

#https://github.com/Akbar30Bill/DOOM_wads
#https://github.com/coelckers/wadext/releases/tag/1.0
#http://www.gamersonlinux.com/forum/threads/brutal-heretic-guide.2473/
