#!/bin/bash

./fifoxRemove
./atualizar
./msfontsInstall
./braveInstall
./chromeInstall

for arg in $@
do 
    case $arg in 
	    "dev")
            echo "Modo Dev"
		    ./vsCodeInstall
            ./arduinoInstall
		    ;;
	    "r")
		    echo "Modo R"
            ./rInstall
		    ;;
    esac
done
