#!/bin/bash

#./fifoxRemove
#./atualizar
#./msfontsInstall
#./braveInstall
#./chromeInstall

for arg in $@
do 
    case $arg in 
	    "dev")
            echo "Modo Dev"
#		    ./codeInstall
#           ./arduinoInstall
		    ;;
	    "r")
		    echo "Modo R"
 #           ./rInstall
		    ;;
		*)
			echo "Comando $arg não encontrado"
    esac
done

echo "Deseja reiniciar?(S/N)"
read result

if [ "$result" == "s" ] || [ "$result" == "S" ]
then
	shutdown -r now
fi