#!/bin/bash

#PS1='\[\e[1;32m\]\342\224\214\342\224\200\[\e[1;32m\][\[\e[1;34m\]\u\[\e[1;32m\]@\[\e[1;34m\]\h\[\e[1;32m\]]\[\e[1;32m\]\342\224\200\[\e[1;32m\][\[\e[1;34m\]\w\[\e[1;32m\]]\[\e[1;32m\]\342\224\200[\[\e[1;34m\]\t\[\e[1;32m\]]\n\[\e[1;32m\]\342\224\224\342\224\200\342\224\200\342\225\274\[\e[1;32m\] \$ \[\e[0m\]'

./firefoxRemove
./atualizar
./numlockxInstall
./msfontsInstall
./braveInstall
./chromeInstall

for arg in $@
do 
    case $arg in 
	    "dev")
		echo "Modo Dev"
    		./codeInstall
		./arduinoInstall
		./qtInstall
	    ;;
	    "r")
		echo "Modo R"
           	./rInstall
	    ;;
        "snap")
            	echo "Modo Snap"
            	./snapInstall
            ;;
		*)
			echo "Comando $arg não encontrado"
    esac
done

sudo apt autoclean
sudo apt autoremove

echo "Deseja reiniciar?(S/N)"
read result

if [ "${result^^}" == "S" ]
then
	shutdown -r now
fi
