#!/bin/sh

#sudo apt-get install build-essential -y

#sudo apt-get install qtcreator -y

#sudo apt-get install qt5-default -y

#sudo apt-get install cmake -y

#sudo apt-get install qttools5-dev -y

#sudo apt-get install qttools5-dev-tools -y

sudo apt install build-essential qtcreator qt5-default cmake qttools5-dev qttools5-dev-tools -y