#!/bin/bash

installed=$(dpkg -s virtualbox | grep "Status: install ok installed")

if [ "$installed" = "" ]; then
	wget https://www.virtualbox.org/download/oracle_vbox_2016.asc
	sudo apt-key add oracle_vbox_2016.asc

	sudo echo "deb http://download.virtualbox.org/virtualbox/debian buster contrib" | sudo tee /etc/apt/sources.list.d/virtualbox.list

	sudo apt-get update
	sudo apt-get install virtualbox-6.1

else
	echo "$0: Programa Já Foi Instalado"
fi